// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/classes" | "/create-class" | "/room"
type AppRouteHandlerRoutes = "/api/auth/logout" | "/api/auth/me" | "/api/auth/session" | "/api/courses" | "/api/courses/[courseId]" | "/api/courses/[courseId]/students" | "/api/cron/cleanup-sessions" | "/api/health" | "/api/questions/[questionId]/answers" | "/api/sessions" | "/api/sessions/[sessionId]" | "/api/sessions/[sessionId]/my-role" | "/api/sessions/[sessionId]/questions" | "/api/sessions/[sessionId]/regenerate-code" | "/api/sessions/[sessionId]/slides" | "/api/sessions/[sessionId]/slides/[slideSetId]/file" | "/api/sessions/join/[code]"
type PageRoutes = never
type LayoutRoutes = "/"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/api/auth/logout": {}
  "/api/auth/me": {}
  "/api/auth/session": {}
  "/api/courses": {}
  "/api/courses/[courseId]": { "courseId": string; }
  "/api/courses/[courseId]/students": { "courseId": string; }
  "/api/cron/cleanup-sessions": {}
  "/api/health": {}
  "/api/questions/[questionId]/answers": { "questionId": string; }
  "/api/sessions": {}
  "/api/sessions/[sessionId]": { "sessionId": string; }
  "/api/sessions/[sessionId]/my-role": { "sessionId": string; }
  "/api/sessions/[sessionId]/questions": { "sessionId": string; }
  "/api/sessions/[sessionId]/regenerate-code": { "sessionId": string; }
  "/api/sessions/[sessionId]/slides": { "sessionId": string; }
  "/api/sessions/[sessionId]/slides/[slideSetId]/file": { "sessionId": string; "slideSetId": string; }
  "/api/sessions/join/[code]": { "code": string; }
  "/classes": {}
  "/create-class": {}
  "/room": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
